---

- name: create the dtool group
  group:
    name: dtool
    state: present

- name: create the dtool user
  user:
    name: dtool
    group: dtool

- name: create ssh key pair
  become: yes
  become_user: dtool
  command: ssh-keygen -t rsa -N "" -f /home/dtool/id_rsa
  args:
    creates: /home/dtool/id_rsa


- name: install dserver and gunicorn
  become: yes
  become_user: dtool
  pip:
    name: [ "dserver", "gunicorn" ]
    virtualenv: /home/dtool/venv

- name: copy over load_env.sh script
  template:
    src: load_env.sh
    dest: /home/dtool/load_env.sh

- name: copy over start_gunicorn.sh script
  copy:
    src: start_gunicorn.sh
    dest: /home/dtool/start_gunicorn.sh

- name: create logs directory
  file:
    path: /home/dtool/logs
    owner: dtool
    group: dtool
    state: directory
