[build-system]
requires = ["setuptools>=42", "setuptools_scm[toml]>=6.3"]
build-backend = "setuptools.build_meta"

[project]
name = "dtool-lookup-server"
description = "Web API to register/lookup/search for dtool dataset metadata"
license = {file = "LICENSE"}
authors = [
    {name = "Tjelvar Olsson", email = "tjelvar.olsson@gmail.com"}
]
dynamic = ["version"]
dependencies = [
        "flask<3",
        "pymongo",
        "alembic",
        "flask-sqlalchemy",
        "flask-migrate",
        "flask-pymongo",
        "flask-marshmallow",
        "flask-smorest",
        "marshmallow-sqlalchemy",
        "flask-cors",
        "dtoolcore>=3.18.0",
        "flask-jwt-extended[asymmetric_crypto]>=4.0",
        "pyyaml"
    ]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
    "sphinxcontrib-spelling",
    "sphinxcontrib-bibtex",
    "myst-parser==3.0.1"
]

[project.urls]
Documentation = "https://dtool-lookup-server.readthedocs.io"
Repository = "https://github.com/jic-dtool/dtool-lookup-server"
Changelog = "https://github.com/jic-dtool/dtool-lookup-server/blob/main/CHANGELOG.rst"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
write_to = "dtool_lookup_server/version.py"

[tool.setuptools]
packages = ["dtool_lookup_server"]

[project.entry-points."flask.commands"]
"base_uri" = "dtool_lookup_server.cli:base_uri_cli"
"user" = "dtool_lookup_server.cli:user_cli"
"config" = "dtool_lookup_server.cli:config_cli"
"dataset" = "dtool_lookup_server.cli:dataset_cli"
