[build-system]
requires = ["setuptools>=42", "setuptools_scm[toml]>=6.3"]
build-backend = "setuptools.build_meta"

[project]
name = "dserver"
description = "Web API to register/lookup/search for dtool dataset metadata"
license = {file = "LICENSE"}
authors = [
    {name = "Tjelvar Olsson", email = "tjelvar.olsson@gmail.com"}
]
dynamic = ["version"]

[project.urls]
Documentation = "https://livmats.github.io/dserver"
Repository = "https://github.com/livMatS/dserver"
Changelog = "https://github.com/livMatS/dserver/blob/main/CHANGELOG.rst"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
write_to = "dserver/version.py"

[tool.setuptools]
packages = ["dserver"]

[tool.poetry.plugins."flask.commands"]
"base_uri" = "dserver.cli:base_uri_cli"
"user" = "dserver.cli:user_cli"
"config" = "dserver.cli:config_cli"
"dataset" = "dserver.cli:dataset_cli"

[tool.poetry.dependencies]
python = "^3.6"
flask = "<3"
pymongo = "*"
alembic = "*"
flask-sqlalchemy = "*"
flask-migrate = "*"
flask-pymongo = "*"
flask-marshmallow = "*"
flask-smorest = "*"
marshmallow-sqlalchemy = "*"
flask-cors = "*"
dtoolcore = ">=3.18.0"
flask-jwt-extended = {version = ">=4.0", extras = ["asymmetric_crypto"]}
pyyaml = "*"
