# Description: python package name (convention: snake_case).
packageName: dtool_lookup_openapi_client

# Description: python project name in setup.py (e.g. petstore-api).
projectName: dtool-lookup-openapi-python-experimental-client

# Description: python package version.
# PackageVersion: 1.0.0

# Description: python package URL.
# packageUrl:  https://github.com/jotelha/dtool-lookup-openapi-python-experimental-client

# Description: Hides the generation timestamp when files are generated.
# hideGenerationTimestamp: true

# Description: Specifies that only a library source code is to be generated.
# generateSourceCodeOnly: false

# Description: use the nose test framework
# useNose: false

# Description: Set the recursion limit. If not set, use the system default value.
# recursionLimit: 

# Description: library template (sub-template) to use: urllib3
library: urllib3

