# Description: python package name (convention: snake_case).
# packageName: dtool_lookup_openapi_client

# Description: python project name in setup.py (e.g. petstore-api).
# projectName: 

# Description: python package version.
# packageVersion: 1.0.0

# Description: python package URL.
# packageUrl: 

# Description: Hides the generation timestamp when files are generated.
# hideGenerationTimestamp: true

# Description: Specifies that only a library source code is to be generated.
# generateSourceCodeOnly: false

# Description: use the nose test framework
# useNose: false

# Description: Set the recursion limit. If not set, use the system default value.
# recursionLimit: 

# Description: library template (sub-template) to use: asyncio, tornado, urllib3
# library: asyncio 
#   will lead to 
#   Exception in thread "main" java.lang.RuntimeException: Only the `urllib3` library is supported in the refactored `python` client generator at the moment. Please fall back to `python-legacy` client generator for the time being. We welcome contributions to add back `asyncio`, `tornado` support to the `python` client generator.

library: urllib3

# Description: when accessing unset attribute, return `None` instead of raising `ApiAttributeError`
# pythonAttrNoneIfUnset: false

# Description: If set to true then the required variables are included as positional arguments in __init__ and _from_openapi_data methods. Note: this can break some composition use cases. To learn more read PR #8802.
# initRequiredVars: false

# Description: If false, the 'additionalProperties' implementation (set to true by default) is compliant with the OAS and JSON schema specifications. If true (default), keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default.
# Available Values:
#    false
#         The 'additionalProperties' implementation is compliant with the OAS and JSON schema specifications.
#    true
#         Keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default. NOTE: this option breaks composition and will be removed in 6.0.0
# disallowAdditionalPropertiesIfNotPresent: false

