name: containers
# tests whether container

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v5.5.1
      with:
        images: ${{ inputs.image }}
        tags: |
          type=raw,value=sha-${{ github.sha }}

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: cache docker layers
      uses: actions/cache@v4.0.2
      env:
        cache-name: cache-docker-layers
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx
        restore-keys: |
          ${{ runner.os }}-buildx

    - name: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/dserver_devel/Dockerfile
        platforms: linux/amd64
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        outputs: type=docker, dest=/tmp/image.tar
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: image digest
      run: echo ${{ steps.docker_build.outputs.digest }}